version: '3'

services:
  covinfo_db_service:
    container_name: covinfo_db
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: covinfo
      POSTGRES_USER: user_covinfo
      POSTGRES_PASSWORD: pgpassword
    ports:
      - '5432:5432'
    networks:
      - network-api
    volumes:
      - ./dados:/var/lib/postgresql/data

  redis:
    container_name: redis_queue
    image: redis
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    ports:
      - '6379:6379'
    networks:
      - network-queue

  covinfo_api_service:
    container_name: covinfo_api_container
    image: covinfo_api_image
    depends_on:
      - covinfo_db_service
      - redis
    command: bash -c "yarn sequelize db:migrate &&  yarn sequelize db:seed:undo:all && yarn sequelize db:seed:all && yarn start"
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    networks:
      - network-api
      - network-queue

  api-queue:
    build: ./
    image: covinfo_image
    command: yarn queue
    depends_on:
      - covinfo_db_service
      - redis
    networks:
      - network-api
      - network-queue

networks:
  network-api:
    external:
      name: network-api
  network-queue:
    external:
      name: network-queue
